# Generated by Django 4.2.16 on 2024-10-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgsqlapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodmodel',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
